// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID         string
	UserID     string
	Status     string
	TotalCents int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type OrderItem struct {
	ID             string
	OrderID        string
	ProductID      string
	ProductName    string
	Quantity       int32
	UnitPriceCents int64
}
