// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPayments = `-- name: CountPayments :one
SELECT COUNT(*)
FROM payments
WHERE ($1::uuid IS NULL OR order_id = $1::uuid)
  AND ($2::uuid IS NULL OR user_id = $2::uuid)
`

type CountPaymentsParams struct {
	OrderID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) CountPayments(ctx context.Context, arg CountPaymentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPayments, arg.OrderID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (order_id, user_id, amount_cents, status, method)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, user_id, amount_cents, status, method, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID     string
	UserID      string
	AmountCents int64
	Status      string
	Method      string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.UserID,
		arg.AmountCents,
		arg.Status,
		arg.Method,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.AmountCents,
		&i.Status,
		&i.Method,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, order_id, user_id, amount_cents, status, method, created_at, updated_at
FROM payments
WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.AmountCents,
		&i.Status,
		&i.Method,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, order_id, user_id, amount_cents, status, method, created_at, updated_at
FROM payments
WHERE ($1::uuid IS NULL OR order_id = $1::uuid)
  AND ($2::uuid IS NULL OR user_id = $2::uuid)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListPaymentsParams struct {
	OrderID pgtype.UUID
	UserID  pgtype.UUID
	Offset  int32
	Limit   int32
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPayments,
		arg.OrderID,
		arg.UserID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.AmountCents,
			&i.Status,
			&i.Method,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $1, updated_at = now()
WHERE id = $2
RETURNING id, order_id, user_id, amount_cents, status, method, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.Status, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.AmountCents,
		&i.Status,
		&i.Method,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
