// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID            string
	Sku           string
	Name          string
	Description   *string
	PriceCents    int64
	StockQuantity int32
	Category      *string
	DeletedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type StockMovement struct {
	ID          string
	ProductID   string
	Delta       int32
	Reason      string
	ReferenceID pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}
