// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products WHERE deleted_at IS NULL
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsByCategory = `-- name: CountProductsByCategory :one
SELECT COUNT(*) FROM products WHERE deleted_at IS NULL AND category = $1
`

func (q *Queries) CountProductsByCategory(ctx context.Context, category *string) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsByCategory, category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (sku, name, description, price_cents, stock_quantity, category)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, sku, name, description, price_cents, stock_quantity, category, created_at, updated_at
`

type CreateProductParams struct {
	Sku           string
	Name          string
	Description   *string
	PriceCents    int64
	StockQuantity int32
	Category      *string
}

type CreateProductRow struct {
	ID            string
	Sku           string
	Name          string
	Description   *string
	PriceCents    int64
	StockQuantity int32
	Category      *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.StockQuantity,
		arg.Category,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.StockQuantity,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStockMovement = `-- name: CreateStockMovement :one
INSERT INTO stock_movements (product_id, delta, reason, reference_id)
VALUES ($1, $2, $3, $4::uuid)
RETURNING id, product_id, delta, reason, reference_id, created_at
`

type CreateStockMovementParams struct {
	ProductID   string
	Delta       int32
	Reason      string
	ReferenceID pgtype.UUID
}

func (q *Queries) CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, createStockMovement,
		arg.ProductID,
		arg.Delta,
		arg.Reason,
		arg.ReferenceID,
	)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Delta,
		&i.Reason,
		&i.ReferenceID,
		&i.CreatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, sku, name, description, price_cents, stock_quantity, category, created_at, updated_at
FROM products
WHERE id = $1 AND deleted_at IS NULL
`

type GetProductByIDRow struct {
	ID            string
	Sku           string
	Name          string
	Description   *string
	PriceCents    int64
	StockQuantity int32
	Category      *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) GetProductByID(ctx context.Context, id string) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.StockQuantity,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductForUpdate = `-- name: GetProductForUpdate :one
SELECT id, sku, name, description, price_cents, stock_quantity, category, created_at, updated_at
FROM products
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

type GetProductForUpdateRow struct {
	ID            string
	Sku           string
	Name          string
	Description   *string
	PriceCents    int64
	StockQuantity int32
	Category      *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) GetProductForUpdate(ctx context.Context, id string) (GetProductForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getProductForUpdate, id)
	var i GetProductForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.StockQuantity,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStockMovements = `-- name: GetStockMovements :many
SELECT id, product_id, delta, reason, reference_id, created_at
FROM stock_movements
WHERE product_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetStockMovementsParams struct {
	ProductID string
	Limit     int32
}

func (q *Queries) GetStockMovements(ctx context.Context, arg GetStockMovementsParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, getStockMovements, arg.ProductID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Delta,
			&i.Reason,
			&i.ReferenceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, sku, name, description, price_cents, stock_quantity, category, created_at, updated_at
FROM products
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32
	Offset int32
}

type ListProductsRow struct {
	ID            string
	Sku           string
	Name          string
	Description   *string
	PriceCents    int64
	StockQuantity int32
	Category      *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.StockQuantity,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT id, sku, name, description, price_cents, stock_quantity, category, created_at, updated_at
FROM products
WHERE deleted_at IS NULL AND category = $3
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsByCategoryParams struct {
	Limit    int32
	Offset   int32
	Category *string
}

type ListProductsByCategoryRow struct {
	ID            string
	Sku           string
	Name          string
	Description   *string
	PriceCents    int64
	StockQuantity int32
	Category      *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]ListProductsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listProductsByCategory, arg.Limit, arg.Offset, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsByCategoryRow
	for rows.Next() {
		var i ListProductsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.StockQuantity,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :execrows
UPDATE products
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $1, description = $2, price_cents = $3, category = $4, updated_at = now()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, sku, name, description, price_cents, stock_quantity, category, created_at, updated_at
`

type UpdateProductParams struct {
	Name        string
	Description *string
	PriceCents  int64
	Category    *string
	ID          string
}

type UpdateProductRow struct {
	ID            string
	Sku           string
	Name          string
	Description   *string
	PriceCents    int64
	StockQuantity int32
	Category      *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.Category,
		arg.ID,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.StockQuantity,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products
SET stock_quantity = $1, updated_at = now()
WHERE id = $2
RETURNING id, sku, name, description, price_cents, stock_quantity, category, created_at, updated_at
`

type UpdateProductStockParams struct {
	StockQuantity int32
	ID            string
}

type UpdateProductStockRow struct {
	ID            string
	Sku           string
	Name          string
	Description   *string
	PriceCents    int64
	StockQuantity int32
	Category      *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (UpdateProductStockRow, error) {
	row := q.db.QueryRow(ctx, updateProductStock, arg.StockQuantity, arg.ID)
	var i UpdateProductStockRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.StockQuantity,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
